<template>
  <po-space>
    <po-avatar
      size="small"
      shape="circle"
      src="https://cy-picgo.oss-cn-hangzhou.aliyuncs.com/jucy-beef-burger.jpg"
    />
    <po-avatar
      shape="circle"
      src="https://cy-picgo.oss-cn-hangzhou.aliyuncs.com/jucy-beef-burger.jpg"
    />
    <po-avatar
      size="large"
      shape="circle"
      src="https://cy-picgo.oss-cn-hangzhou.aliyuncs.com/jucy-beef-burger.jpg"
    />
    <po-avatar
      :size="60"
      shape="circle"
      src="https://cy-picgo.oss-cn-hangzhou.aliyuncs.com/jucy-beef-burger.jpg"
    />
  </po-space>
</template>
