// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'demo-popper-basic': typeof import('@/demo/popper/demos/demo-popper-basic.vue')['default']
    'demo-table-basic': typeof import('@/demo/table/demos/demo-table-basic.vue')['default']
    'demo-tooltip-basic': typeof import('@/demo/tooltip/demos/demo-tooltip-basic.vue')['default']
    PoPopper: typeof import('pomelo-plus')['PoPopper']
    PoPopperContent: typeof import('pomelo-plus')['PoPopperContent']
    PoPopperTrigger: typeof import('pomelo-plus')['PoPopperTrigger']
    PoTable: typeof import('pomelo-plus')['PoTable']
    PoTableColumn: typeof import('pomelo-plus')['PoTableColumn']
    PoTooltip: typeof import('pomelo-plus')['PoTooltip']
  }
}

export { }
