// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'demo-popper-basic': typeof import('@/demo/popper/demos/demo-popper-basic.vue')['default']
    PoPopper: typeof import('@/components/popper')['PoPopper']
    PoPopperContent: typeof import('@/components/popper')['PoPopperContent']
    PoPopperTrigger: typeof import('@/components/popper')['PoPopperTrigger']
  }
}

export { }
