// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    PoAffix: typeof import('@pomelo-plus/components/affix')['default']
    PoAlert: typeof import('@pomelo-plus/components/alert')['default']
    PoAnchor: typeof import('@pomelo-plus/components/anchor')['default']
    PoAnchorLink: typeof import('@pomelo-plus/components/anchor-link')['default']
    PoAvatar: typeof import('@pomelo-plus/components/avatar')['default']
    PoBadge: typeof import('@pomelo-plus/components/badge')['default']
    PoButton: typeof import('@pomelo-plus/components/button')['default']
    PoButtonGroup: typeof import('@pomelo-plus/components/button-group')['default']
    PoCheckbox: typeof import('@pomelo-plus/components/checkbox')['default']
    PoDivider: typeof import('@pomelo-plus/components/divider')['default']
    PoIcon: typeof import('@pomelo-plus/components/icon')['default']
    PoProgress: typeof import('@pomelo-plus/components/progress')['default']
    PoSpace: typeof import('@pomelo-plus/components/space')['default']
    PoTooltip: typeof import('pomelo-plus')['default']
    PoUpload: typeof import('@pomelo-plus/components/upload')['default']
  }
}

export {}
